In [495]:
import pandas as pd

amazon_data = pd.read_csv("/Users/yingzhu/Desktop/sentiment labelled sentences/amazon_cells_labelled.txt", header=None, \
                    delimiter="\t",  quoting=3)    

yelp_data = pd.read_csv("/Users/yingzhu/Desktop/sentiment labelled sentences/yelp_labelled.txt", header=None, \
                    delimiter="\t",  quoting=3)  

imdb_data = pd.read_csv("/Users/yingzhu/Desktop/sentiment labelled sentences/imdb_labelled.txt", header=None, \
                    delimiter="\t",  quoting=3)  


In [496]:
# Check whether the labels balanced. Report the ratio between two labels
amazon_ratio = sum(amazon_data[1]==1)/sum(amazon_data[1]==0)
print("amazon data is balanced: ",amazon_ratio==1)
print("amazon data's ratio is ", amazon_ratio)

yelp_ratio = sum(yelp_data[1]==1)/sum(yelp_data[1]==0)
print("yelp data is balanced: ",yelp_ratio==1)
print("yelp data's ratio is ", yelp_ratio)

imdb_ratio = sum(imdb_data[1]==1)/sum(imdb_data[1]==0)
print("imdb data is balanced: ",imdb_ratio==1)
print("imdb data's ratio is ", imdb_ratio)

amazon data is balanced:  True
amazon data's ratio is  1.0
yelp data is balanced:  True
yelp data's ratio is  1.0
imdb data is balanced:  True
imdb data's ratio is  1.0


In [497]:
# Add header to Dataframe
amazon_data.columns = ["sentence","score"]
yelp_data.columns = ["sentence","score"]
imdb_data.columns = ["sentence","score"]

In [498]:
# Lowercase all the words
amazon_data['sentence'] = amazon_data['sentence'].str.lower()
yelp_data['sentence'] = yelp_data['sentence'].str.lower()
imdb_data['sentence'] = imdb_data['sentence'].str.lower()
print(amazon_data['sentence'][0])

so there is no way for me to plug it in here in the us unless i go by a converter.


In [341]:
# try some other lemmatization 
#import nltk
#nltk.download('wordnet')
#from nltk.stem.wordnet import WordNetLemmatizer
#lmtzr = WordNetLemmatizer()
#def lemm(s):
 #   s_split = s.split()
  #  for i in range(len(s_split)):
   #     s_split[i] = lmtzr.lemmatize(s_split[i])
    #return " ".join(s_split)

[nltk_data] Downloading package wordnet to /Users/yingzhu/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [342]:
#amazon_data['sentence'] =amazon_data['sentence'].apply(lemm)
#yelp_data['sentence'] =yelp_data['sentence'].apply(lemm)
#imdb_data['sentence'] =imdb_data['sentence'].apply(lemm)

In [432]:
#amazon_data['sentence'].head(20)

In [499]:
# Strip punctuation
import string
def remove_punctuation(s):
    s = ''.join([i for i in s if i not in frozenset(string.punctuation)])
    return s

In [500]:
amazon_data['sentence'] = amazon_data['sentence'].apply(remove_punctuation)
yelp_data['sentence'] = yelp_data['sentence'].apply(remove_punctuation)
imdb_data['sentence'] =imdb_data['sentence'].apply(remove_punctuation)
amazon_data['sentence'].head(10)

0    so there is no way for me to plug it in here i...
1                            good case excellent value
2                                great for the jawbone
3    tied to charger for conversations lasting more...
4                                     the mic is great
5    i have to jiggle the plug to get it to line up...
6    if you have several dozen or several hundred c...
7              if you are razr owneryou must have this
8                    needless to say i wasted my money
9                       what a waste of money and time
Name: sentence, dtype: object

In [526]:
# Strip the stop word
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
cachedStopWords = stopwords.words("english")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/yingzhu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [502]:
def stripstop(s):
    s_split = s.split()
    s_split =' '.join([i for i in s_split if i not in cachedStopWords])
    return s_split

In [503]:
amazon_data['sentence'] = amazon_data['sentence'].apply(stripstop)
yelp_data['sentence'] = yelp_data['sentence'].apply(stripstop)
imdb_data['sentence'] = imdb_data['sentence'].apply(stripstop)

In [504]:
amazon_data['sentence'].head(10)

0                      way plug us unless go converter
1                            good case excellent value
2                                        great jawbone
3    tied charger conversations lasting 45 minutesm...
4                                            mic great
5         jiggle plug get line right get decent volume
6    several dozen several hundred contacts imagine...
7                                   razr owneryou must
8                            needless say wasted money
9                                     waste money time
Name: sentence, dtype: object

In [505]:
# Lemmatization of all the words
# User Porter Stemmer
from nltk.stem.porter import PorterStemmer
porter_stemmer = PorterStemmer()
def lemmP(s):
    s_split=s.split()
    for j in range(len(s_split)):
        s_split[j]= porter_stemmer.stem(s_split[j]) 
    return " ".join(s_split)
amazon_data['sentence'] = amazon_data['sentence'][0:len(amazon_data['sentence'])].apply(lemmP)
yelp_data['sentence'] = yelp_data['sentence'][0:len(yelp_data['sentence'])].apply(lemmP)
imdb_data['sentence'] = imdb_data['sentence'][0:len(imdb_data['sentence'])].apply(lemmP)
amazon_data['sentence'][0:20]

0                         way plug us unless go convert
1                                  good case excel valu
2                                          great jawbon
3      tie charger convers last 45 minutesmajor problem
4                                             mic great
5            jiggl plug get line right get decent volum
6     sever dozen sever hundr contact imagin fun sen...
7                                      razr ownery must
8                               needless say wast money
9                                       wast money time
10                                  sound qualiti great
11             impress go origin batteri extend batteri
12    two seper mere 5 ft start notic excess static ...
13                                  good qualiti though
14                          design odd ear clip comfort
15                highli recommend one blue tooth phone
16                                   advis everyon fool
17                                             f

In [506]:
# Split training and testing set (first 400 label 0 and 400 label 1 as training, the rest as test)
import numpy as np
from sklearn.model_selection import train_test_split
amazon_train,amazon_test = train_test_split(amazon_data,train_size =0.8,stratify =amazon_data['score'])
yelp_train,yelp_test = train_test_split(yelp_data,train_size =0.8,stratify =yelp_data['score'])
imdb_train,imdb_test = train_test_split(imdb_data,train_size =0.8,stratify =imdb_data['score'])
print(sum(amazon_train['score']==1),sum(amazon_test['score']==1))
print(sum(yelp_train['score']==1),sum(yelp_test['score']==1))
print(sum(imdb_train['score']==1),sum(imdb_test['score']==1))

400 100
400 100
400 100


In [507]:
# Bag of Word model 
def getunique(data):
    first=[]
    for i in data:
        second=i.split()
        first = list(set(first +second)) # union
    return first

In [508]:
dictionary1 = getunique(amazon_train['sentence'])
dictionary2 = getunique(yelp_train['sentence'])
dictionary3 = getunique(imdb_train['sentence'])

In [509]:
total = list(set(dictionary1+dictionary2+dictionary3))
print(len(total))

3691


In [510]:
# Count appearance in the dictionary
training= [amazon_train, yelp_train, imdb_train]
training = pd.concat(training)
print(training.shape)

test= [amazon_test, yelp_test, imdb_test]
test = pd.concat(test)
print(test.shape)

(2400, 2)
(600, 2)


In [511]:
def featurevector(length, s, dic):
    occur=[]
    for i in range(len(s)):
        row = [int(0)]*length
        s_split = s[i].split()
        for j in range(len(s_split)):
            if(s_split[j] in dic):
                row[total.index(s_split[j])]+=int(1)
        occur.append(row)
    return occur

In [512]:
train_sentence = list(training['sentence'])
train_score = list(training['score'])
test_sentence = list(test['sentence'])
test_score = list(test['score'])
train_occur= featurevector(len(total),train_sentence,total)
test_occur = featurevector(len(total),test_sentence,total)

In [513]:
pd.DataFrame(train_occur[100:102])

0     1     2     3     4     5     6     7     8     9     ...   3681  \
0     0     0     0     0     0     0     0     0     0     0  ...      0   
1     0     0     0     0     0     0     0     0     0     0  ...      0   

   3682  3683  3684  3685  3686  3687  3688  3689  3690  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     1     0     0     0     0     0  

[2 rows x 3691 columns]

In [217]:
print(np.nonzero(train_occur[100]))
print(np.nonzero(train_occur[101]))

(array([ 229, 1017, 1243, 1346, 1774, 1968, 2153, 2213, 2285, 2333, 2753,
       2777, 3041, 3280, 3612]),)
(array([ 105,  790, 1478, 1683, 1884, 1903, 1932, 2034, 2105, 2355, 2396,
       3237, 3391]),)


In [514]:
# pick your postprocessing strategy
#(1) log normalization
import math
def lognorm(vector):
    res=[]
    for i in range(len(vector)):
        temp =[]
        for j in range(len(vector[i])):
            temp.append(math.log1p(vector[i][j]+1))
        res.append(temp)
    return res

In [515]:
#(2) l2 normalization
def l2norm(vector):
    res=[]
    for i in range(len(vector)):
        deno = np.linalg.norm(vector[i])
        if deno==0:
            res.append(vector[i])
            continue
        temp=[]
        for j in range(len(vector[i])):
            temp.append(vector[i][j]/deno)
        res.append(temp)
    return res

In [516]:
#(3) l1 normalization:
def l1norm(vector):
    res=[]
    for i in range(len(vector)):
        deno=np.linalg.norm(vector[i], ord=1)
        if deno==0:
            res.append(vector[i])
            continue
        temp=[]
        for j in range(len(vector[i])):
            temp.append(vector[i][j]/deno)
        res.append(temp)
    return res

In [517]:
#(4) subtracting mean and divide by variance
def meansubtract(vector):
    res=[]
    for i in range(len(vector)):
        vec_mean = np.mean(vector[i])
        vec_std = np.std(vector[i])
        if vec_std==0:
            res.append(vector[i])
            continue
        temp =[]
        for j in range(len(vector[i])):
            temp.append((vector[i][j]-vec_mean)/vec_std)
        res.append(temp)
    return res

In [518]:
train_occur_log = lognorm(train_occur)
train_occur_l1 = l1norm(train_occur)
train_occur_l2 = l2norm(train_occur)
train_occur_meansub = meansubtract(train_occur)

In [253]:
print(np.var(train_occur_log))
print(np.var(train_occur_l1))
print(np.var(train_occur_l2))
print(np.var(train_occur_meansub))

0.000282557225166
6.97856748766e-05
0.000272670768
1.0


In [519]:
# sentiment prediction: train a logstic regression model 
from sklearn.linear_model import LogisticRegression as logR
from sklearn.metrics import confusion_matrix as cm

In [520]:
test_occur_log = lognorm(train_occur) 
ls = logR() 
ls.fit(train_occur_log,train_score) 
ls_score = ls.score(test_occur_log,test_score) 
print(ls_score)

ValueError: Found input variables with inconsistent numbers of samples: [600, 2400]

test_occur_log = lognorm(train_occur)
ls = logR()
ls.fit(train_occur_log,train_score)
ls_score = ls.score(test_occur_log,test_score)
print(ls_score)

In [280]:
test_occur_l1 = l1norm(test_occur)
ls = logR()
ls.fit(train_occur_l1,train_score)
ls_score = ls.score(test_occur_l1,test_score)
print(ls_score)

0.786666666667


In [285]:
test_occur_l2 = l2norm(test_occur)
ls = logR()
ls.fit(train_occur_l2,train_score)
ls_score = ls.score(test_occur_l2,test_score)
print(ls_score)
# confusion matrix
test_pred = ls.predict(test_occur_l2)
cm(test_score,test_pred)

0.816666666667


array([[255,  45],
       [ 65, 235]])

In [524]:
# show most siginificant words (showing top 10)
logR_coef = ls.coef_[0]
rank_coef = np.argsort(logR_coef)
for i in range(10):
    print(total[rank_coef[-1*i]])

bad
great
love
excel
nice
best
good
amaz
wonder
happi


In [273]:
test_occur_log = lognorm(test_occur)
ls = logR()
ls.fit(train_occur_log,train_score)
ls_score = ls.score(test_occur_log,test_score)
print(ls_score)

0.81


In [279]:
test_occur_meansub = meansubtract(test_occur)
ls = logR()
ls.fit(train_occur_meansub,train_score)
ls_score = ls.score(test_occur_meansub,test_score)
print(ls_score)

0.733333333333


In [384]:
# Naive Bayes
from sklearn import cross_validation
from sklearn.naive_bayes import BernoulliNB
clf_B = BernoulliNB()
clf_B.fit(train_occur_l2,train_score)
clf_Bscore = clf_B.score(test_occur_l2,test_score)
clf_Bscore

0.81999999999999995

In [375]:
# (g)N-gram Model
# n gram bagging
def getNgram(data, n):
    res=[]
    for i in range(len(data)):
        temp_data = data[i].split()
        temp_res=[]
        if len(temp_data)<=n:
            res.append([data[i]])
            continue
        for j in range(len(temp_data)-n+1):
            temp_res.append(" ".join(temp_data[j:j+n]))
        res.append(temp_res)   
    return res


In [352]:
# get featire vector based on n gram
def getunique_ngram(data):
    first=[]
    for i in data:
        first = list(set(first + i)) # union
    return first

In [360]:
def featurevector_ngram(length, s, dic):
    occur=[]
    for i in range(len(s)):
        row = [int(0)]*length
        for j in range(len(s[i])):
            if(s[i][j] in dic):
                row[dic.index(s[i][j])]+=int(1)
        occur.append(row)
    return occur

In [376]:
train_gram2 = getNgram(train_sentence,2)
print(train_gram2[:5])
test_gram2 = getNgram(test_sentence,2)
print(test_gram2[:5])

[['thank great', 'great servic'], ['pair headphon', 'headphon worst', 'worst ever', 'ever soundwis'], ['good product', 'product good', 'good seller'], ['impress'], ['found product', 'product waaay', 'waaay big']]
[['phone work', 'work great'], ['use dirti'], ['great phone'], ['hate earbug', 'earbug avoid', 'avoid phone', 'phone mean'], ['headset easi', 'easi use', 'use everyon', 'everyon love']]


In [525]:
total_gram2 = getunique_ngram(train_gram2)
print(len(total_gram2))

11336


In [378]:
train_occur_gram2= featurevector_ngram(len(total_gram2),train_gram2,total_gram2)
test_occur_gram2= featurevector_ngram(len(total_gram2),test_gram2,total_gram2)

In [379]:
# logistic regression for gram2
test_occur_gram2_l2 = l2norm(test_occur_gram2)
train_occur_gram2_l2 = l2norm(train_occur_gram2)
ls_gram2 = logR()
ls_gram2.fit(train_occur_gram2_l2,train_score)
ls_gram2_score = ls_gram2.score(test_occur_gram2_l2,test_score)
print(ls_gram2_score)
# confusion matrix
test_pred_gram2 = ls_gram2.predict(test_occur_gram2_l2)
cm(test_score,test_pred_gram2)

0.665


array([[266,  34],
       [167, 133]])

In [380]:
# show most siginificant words (showing top 10) for gram2
logR_coef_gram2 = ls_gram2.coef_[0]
rank_coef_gram2 = np.argsort(logR_coef_gram2)
for i in range(10):
    print(total_gram2[rank_coef_gram2[-1*i]])

wast time
work great
highli recommend
great phone
work fine
realli good
one best
love place
good qualiti
food good


In [385]:
# Naive Bayes
# Naive Bayes
clf_B_gram2 = BernoulliNB()
clf_B_gram2.fit(train_occur_gram2_l2,train_score)
clf_B_gram2score = clf_B_gram2.score(test_occur_gram2_l2,test_score)
clf_B_gram2score

0.65666666666666662

In [476]:
# (h) PCA for bag of words model
def PCA(data,n):
    demean_data = data-np.mean(data,axis=0)
    cov = np.cov(data,rowvar=False)
    e_val,e_vec = np.linalg.eigh(cov)
    asc_index = np.argsort(e_val)[::-1]
    val= e_val[asc_index]
    vec= e_vec[:,asc_index]
    e_val = val[:n]
    e_vec = vec[:,:n]
    return np.dot(data,np.transpose(e_vec.T))

In [449]:
# 10/50/100
def log_res(train_data,train_out, test_data,test_out):
    ls = logR()
    ls.fit(train_data,train_out)
    ls_score= ls.score(test_data,test_out)
    print("Logistic regression accuracy: ", ls_score)
    test_pred = ls.predict(test_data)
    print(cm(test_score,test_pred))
    

In [477]:
train_pac10 = PCA(train_occur_l2,10)
test_pac10 = PCA(test_occur_l2,10)
#train_pac50 = PCA(train_occur_l2,50)
#test_pac50 = PCA(test_occur_l2,50)
#train_pac100 = PCA(train_occur_l2,100)
#test_pac100 = PCA(test_occur_l2,100)

ValueError: operands could not be broadcast together with shapes (2400,10) (2400,3662) 

In [453]:
log_res(train_pac10,train_score,test_pac10,test_score)

Logistic regression accuracy:  0.585
[[249  51]
 [198 102]]


In [454]:
log_res(train_pac50,train_score,test_pac50,test_score)

Logistic regression accuracy:  0.581666666667
[[211  89]
 [162 138]]


In [455]:
log_res(train_pac100,train_score,test_pac100,test_score)

Logistic regression accuracy:  0.595
[[216  84]
 [159 141]]
